language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_pauzin_lab
  - make -j
  - ./vectortest/vectortest
  - ./matrixtest/matrixtest
  - ./stacktest/stacktest
  - ./multistacktest/multistacktest
  - ./queuetest/queuetest
  - ./datlisttest/datlisttest
notifications:
  email: false

